name: Manual Trigger (Workflow Dispatch)

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm this run'
        required: true
        default: 'Cancel'

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code.
        uses: actions/checkout@v3

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Initialize terraform
        run: terraform init

      - name: Check inputs
        if: ${{ github.event.inputs.confirmation != 'destroy'}}
        run: |
          echo "Confirmation input not received. Exiting workflow."
          echo ${{ github.ref_name }}
          exit 1

      - name: Destroy current state
        run: terraform destroy -auto-approve